In [1]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
#list to array conversion
list1=[11,22,33,44]
array1=np.array(list1)
array1

array([11, 22, 33, 44])

In [7]:
list2=[[11,12,13],[22,23,24],[33,34,35]]
np.array(list2)

array([[11, 12, 13],
       [22, 23, 24],
       [33, 34, 35]])

In [9]:
#creation of array using builtin methods

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.linspace(1,20,4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [25]:
#to create an identity matrix

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#to create an array with random nos of uniform distribution

In [35]:
np.random.rand(3,2)

array([[0.13965103, 0.63447791],
       [0.3900619 , 0.13533378],
       [0.81836422, 0.90205705]])

In [37]:
np.random.randint(1,20,5)

array([ 7,  5,  2,  5, 13])

In [39]:
#attributes and method of numoy array

In [49]:
arr1=np.arange(10,30,2)
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [51]:
arr1.reshape(2,5)

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [53]:
arr1.max()

28

In [55]:
arr1.min()

10

In [57]:
arr1.argmax()

9

In [59]:
arr1.argmin()

0

In [63]:
#to find shape of an array
arr1.shape

(10,)

In [69]:
a=arr1.reshape(5,2)

In [71]:
a.shape

(5, 2)

In [75]:
#to find data types
arr1.dtype

dtype('int32')

In [83]:
#slicing a particular element
arr1[3]

16

In [81]:
arr1[2:4]

array([14, 16])

In [85]:
#replacing element/s
arr1[2:4]=0
arr1

array([10, 12,  0,  0, 18, 20, 22, 24, 26, 28])

In [91]:
arr1[:]=10
arr1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [95]:
#to create a new array
arr1_copy=arr1.copy()
arr1_copy[2:7]=15
arr1_copy

array([10, 10, 15, 15, 15, 15, 15, 10, 10, 10])

In [101]:
#2D array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
arr2[1][1]

5

In [111]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [123]:
#conditional selection
bool_arr=arr1>15
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False])

In [125]:
arr1[arr1>15]

array([], dtype=int32)

In [127]:
#arithmetic operations
arr1+arr1

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [129]:
arr1*arr1

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [131]:
#transpose
arr1.T

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [135]:
#universal functions
np.sqrt(arr1)

array([3.16227766, 3.16227766, 3.16227766, 3.16227766, 3.16227766,
       3.16227766, 3.16227766, 3.16227766, 3.16227766, 3.16227766])

In [137]:
np.exp(arr1)

array([22026.46579481, 22026.46579481, 22026.46579481, 22026.46579481,
       22026.46579481, 22026.46579481, 22026.46579481, 22026.46579481,
       22026.46579481, 22026.46579481])

In [139]:
np.sin(arr2)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [141]:
np.log(arr2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [143]:
np.dot(arr2,arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [145]:
np.multiply(arr2,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [147]:
#to flatten out an array into single dimension
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
#same as ravel fn
arr2.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [153]:
arr2.mean()

5.0